<a href="https://colab.research.google.com/github/Mysterious-27/21AI72-NN-and-DL/blob/main/p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Taking our own input


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
# def sigmoid(x):
#     return tf.keras.activations.sigmoid(x)

# def tanh(x):
#     return tf.keras.activations.tanh(x)

# def relu(x):
#     return tf.keras.activations.relu(x)

# def softmax(x):
#     return tf.keras.activations.softmax(x)

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

def relu(x):
    return np.maximum(0, x)
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / exp_x.sum()

In [ ]:
x = np.linspace(-10, 10, 100)
x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [ ]:
y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)
y_softmax = softmax(x)
y_sigmoid, y_tanh, y_relu, y_softmax

(array([4.53978687e-05, 5.55606489e-05, 6.79983174e-05, 8.32200197e-05,
        1.01848815e-04, 1.24647146e-04, 1.52547986e-04, 1.86692945e-04,
        2.28478855e-04, 2.79614739e-04, 3.42191434e-04, 4.18766684e-04,
        5.12469082e-04, 6.27124987e-04, 7.67413430e-04, 9.39055039e-04,
        1.14904229e-03, 1.40591988e-03, 1.72012560e-03, 2.10440443e-03,
        2.57431039e-03, 3.14881358e-03, 3.85103236e-03, 4.70911357e-03,
        5.75728612e-03, 7.03711536e-03, 8.59898661e-03, 1.05038445e-02,
        1.28252101e-02, 1.56514861e-02, 1.90885420e-02, 2.32625358e-02,
        2.83228820e-02, 3.44451957e-02, 4.18339400e-02, 5.07243606e-02,
        6.13831074e-02, 7.41067363e-02, 8.92170603e-02, 1.07052146e-01,
        1.27951705e-01, 1.52235823e-01, 1.80176593e-01, 2.11963334e-01,
        2.47663801e-01, 2.87185901e-01, 3.30246430e-01, 3.76354517e-01,
        4.24816868e-01, 4.74768924e-01, 5.25231076e-01, 5.75183132e-01,
        6.23645483e-01, 6.69753570e-01, 7.12814099e-01, 7.523361

In [ ]:
# # Plot the results
# plt.figure(figsize=(12, 8))

# plt.subplot(2, 2, 1)
# plt.plot(x, y_sigmoid)
# plt.title('Sigmoid Activation Function')

# plt.subplot(2, 2, 2)
# plt.plot(x, y_tanh)
# plt.title('Tanh Activation Function')

# plt.subplot(2, 2, 3)
# plt.plot(x, y_relu)
# plt.title('ReLU Activation Function')

# plt.subplot(2, 2, 4)
# plt.plot(x, y_softmax)
# plt.title('Softmax Activation Function')

# plt.show()

In [ ]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0



# print(tf.nn.tanh(predictions).numpy())

# loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

print(model.evaluate(x_test,  y_test, verbose=2))

# probability_model = tf.keras.Sequential([
#   model,
#   tf.keras.layers.Softmax()
# ])
# print(probability_model(x_test[:5]))



Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.7842 - loss: 0.6523
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8076 - loss: 0.6031
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8274 - loss: 0.5412
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8387 - loss: 0.5103
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8508 - loss: 0.4706
313/313 - 1s - 2ms/step - accuracy: 0.9387 - loss: 0.2327
[0.23273546993732452, 0.9387000203132629]


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='tanh'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
print("Predictions: ", predictions)

Predictions:  [[-0.09900242  0.46363515 -0.3012781   0.23611489 -0.45185992  0.6452898
  -0.9504489  -0.3791827   0.8060753   0.4489795 ]]


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
print("Predictions: ", predictions)

Predictions:  [[ 0.1691619  -0.0273245   0.10333499 -0.4655018  -0.20277794 -0.03630955
   0.7308886  -0.08672032  0.21913233 -0.20052204]]


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='sigmoid'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
print("Predictions: ", predictions)

Predictions:  [[-0.28386262 -0.79435563 -0.5966868   1.4479383   1.0309739  -0.24247704
   0.162836   -0.5787261  -0.5570216   0.8040716 ]]


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='softmax'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
print("Predictions: ", predictions)

Predictions:  [[ 0.00417044 -0.01521724 -0.00610546  0.0047087  -0.02625129  0.00423488
   0.00844995  0.0061378   0.00619716 -0.0174382 ]]


#Taking input from an existing dataset


In [1]:
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Activation Functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

def relu(x):
    return np.maximum(0, x)

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # for numerical stability
    return e_x / e_x.sum(axis=1, keepdims=True)

# Display the first few samples of the dataset
print("Input Values (first 5 samples):")
print(pd.DataFrame(X, columns=iris.feature_names).head())

# Calculate and display outputs for the first sample
sample = X[:5]  # Taking first 5 samples for demonstration

print("\nSigmoid Output:")
print(sigmoid(sample))

print("\nTanh Output:")
print(tanh(sample))

print("\nReLU Output:")
print(relu(sample))

# Softmax expects a 2D array, using the first few samples
print("\nSoftmax Output:")
print(softmax(sample))


Input Values (first 5 samples):
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Sigmoid Output:
[[0.9939402  0.97068777 0.80218389 0.549834  ]
 [0.99260846 0.95257413 0.80218389 0.549834  ]
 [0.9909867  0.96083428 0.78583498 0.549834  ]
 [0.9900482  0.95689275 0.81757448 0.549834  ]
 [0.99330715 0.97340301 0.80218389 0.549834  ]]

Tanh Output:
[[0.99992566 0.9981779  0.88535165 0.19737532]
 [0.9998891  0.99505475 0.88535165 0.19737532]
 [0.99983457 0.9966824  0.86172316 0.19737532]
 [0.99979794 0.99594936 0.90514825 0.19737532]
 [0.9999092  0.99850794 0.88535165 0.19737532]]

ReLU Out

#P3


In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

class NeuralNetwork:
    def __init__(self, input_size, hidden_layers, output_size):
        self.input_size = input_size
        self.hidden_layers = hidden_layers
        self.output_size = output_size
        self.weights = []
        self.biases = []

        # Initialize layer sizes
        layer_sizes = [input_size] + hidden_layers + [output_size]

        # Xavier initialization for weights and biases
        for i in range(len(layer_sizes) - 1):
            limit = np.sqrt(6 / (layer_sizes[i] + layer_sizes[i + 1]))
            weight = np.random.uniform(-limit, limit, (layer_sizes[i], layer_sizes[i + 1]))
            bias = np.zeros((1, layer_sizes[i + 1]))
            self.weights.append(weight)
            self.biases.append(bias)

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def sigmoid_derivative(self, z):
        return z * (1 - z)

    def feedforward(self, X):
        self.a = [X]
        for weight, bias in zip(self.weights, self.biases):
            z = self.a[-1].dot(weight) + bias
            a = self.sigmoid(z)
            self.a.append(a)
        return self.a[-1]

    def backpropagate(self, X, y, learning_rate):
        output = self.feedforward(X)
        output_error = y - output
        deltas = [output_error * self.sigmoid_derivative(output)]

        # Backpropagation
        for i in reversed(range(len(self.weights) - 1)):
            error = deltas[-1].dot(self.weights[i + 1].T)
            delta = error * self.sigmoid_derivative(self.a[i + 1])
            deltas.append(delta)

        deltas.reverse()

        # Update weights and biases
        for i in range(len(self.weights)):
            self.weights[i] += self.a[i].T.dot(deltas[i]) * learning_rate
            self.biases[i] += np.sum(deltas[i], axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            self.backpropagate(X, y, learning_rate)
            if epoch % 1000 == 0:
                loss = np.mean(np.square(y - self.feedforward(X)))
                print(f'Epoch {epoch}, Loss: {loss}')

if __name__ == "__main__":
    data = load_iris()
    X = data.data
    y = data.target.reshape(-1, 1)

    # One-hot encoding the labels
    encoder = OneHotEncoder(sparse_output=False)
    y = encoder.fit_transform(y)

    # Create and train the neural network
    nn = NeuralNetwork(input_size=4, hidden_layers=[10, 10, 10, 10], output_size=3)
    nn.train(X, y, epochs=10000, learning_rate=0.01)


Epoch 0, Loss: 0.2732390192573928
Epoch 1000, Loss: 0.12326484948717387
Epoch 2000, Loss: 0.012460673982972188
Epoch 3000, Loss: 0.015928069988262298
Epoch 4000, Loss: 0.01209105861454704
Epoch 5000, Loss: 0.008140564886561999
Epoch 6000, Loss: 0.0115295175526929
Epoch 7000, Loss: 0.0048605017647235975
Epoch 8000, Loss: 0.004592763595337956
Epoch 9000, Loss: 0.004523608647455111


In [8]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights = [np.random.uniform(-1, 1, (input_size, hidden_size)),
                        np.random.uniform(-1, 1, (hidden_size, output_size))]
        self.biases = [np.zeros((1, hidden_size)), np.zeros((1, output_size))]

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def train(self, X, y, epochs, lr):
        for _ in range(epochs):
            # Forward pass
            activations = [X]  # Store activations of each layer
            a = X
            for w, b in zip(self.weights, self.biases):
                z = a.dot(w) + b
                a = self.sigmoid(z)
                activations.append(a)

            # Backpropagation
            error = y - activations[-1]  # Error at the output layer

            for i in reversed(range(len(self.weights))):
                # Calculate delta for current layer
                if i == len(self.weights) - 1:  # Output layer
                    delta = error * activations[-1] * (1 - activations[-1])
                else:  # Hidden layer
                    delta = error.dot(self.weights[i + 1].T) * activations[i + 1] * (1 - activations[i + 1])

                # Update weights and biases for current layer
                self.weights[i] += activations[i].T.dot(delta) * lr  # Use activations of previous layer for weight update
                self.biases[i] += np.sum(delta, axis=0, keepdims=True) * lr

                # Update error for the next layer (previous in the reversed loop)
                error = delta



In [5]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

class SimpleNN:
    def __init__(self, input_size, hidden_size, output_size):
        self.W1 = np.random.randn(input_size, hidden_size)
        self.b1 = np.zeros((1, hidden_size))
        self.W2 = np.random.randn(hidden_size, output_size)
        self.b2 = np.zeros((1, output_size))

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def train(self, X, y, epochs, lr):
        for _ in range(epochs):
            z1 = X.dot(self.W1) + self.b1
            a1 = self.sigmoid(z1)
            z2 = a1.dot(self.W2) + self.b2
            a2 = self.sigmoid(z2)
            error = y - a2
            self.W2 += a1.T.dot(error * a2 * (1 - a2)) * lr
            self.b2 += np.sum(error * a2 * (1 - a2), axis=0, keepdims=True) * lr
            self.W1 += X.T.dot((error * a2 * (1 - a2)).dot(self.W2.T) * a1 * (1 - a1)) * lr
            self.b1 += np.sum((error * a2 * (1 - a2)).dot(self.W2.T) * a1 * (1 - a1), axis=0, keepdims=True) * lr

if __name__ == "__main__":
    data = load_iris()
    X = data.data
    y = OneHotEncoder(sparse_output=False).fit_transform(data.target.reshape(-1, 1))
    nn = SimpleNN(input_size=4, hidden_size=3, output_size=3)
    nn.train(X, y, epochs=1000, lr=0.01)


In [7]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

class SimpleNN:
    def __init__(self, input_size, hidden_size, output_size):
        self.W1 = np.random.randn(input_size, hidden_size)
        self.b1 = np.zeros((1, hidden_size))
        self.W2 = np.random.randn(hidden_size, output_size)
        self.b2 = np.zeros((1, output_size))

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def train(self, X, y, epochs, lr):
        for _ in range(epochs):
            z1 = X.dot(self.W1) + self.b1
            a1 = self.sigmoid(z1)
            z2 = a1.dot(self.W2) + self.b2
            a2 = self.sigmoid(z2)
            error = y - a2
            self.W2 += a1.T.dot(error * a2 * (1 - a2)) * lr
            self.b2 += np.sum(error * a2 * (1 - a2), axis=0, keepdims=True) * lr
            self.W1 += X.T.dot((error * a2 * (1 - a2)).dot(self.W2.T) * a1 * (1 - a1)) * lr
            self.b1 += np.sum((error * a2 * (1 - a2)).dot(self.W2.T) * a1 * (1 - a1), axis=0, keepdims=True) * lr

        # Print final predictions
        final_predictions = self.sigmoid(a2)
        print("Final Predictions (first 5):", final_predictions[:5])

if __name__ == "__main__":
    data = load_iris()
    X = data.data
    y = OneHotEncoder(sparse_output=False).fit_transform(data.target.reshape(-1, 1))
    nn = SimpleNN(input_size=4, hidden_size=3, output_size=3)
    nn.train(X, y, epochs=1000, lr=0.01)


Final Predictions (first 5): [[0.58256462 0.58257126 0.58257155]
 [0.58256367 0.58257717 0.58256906]
 [0.58255778 0.58259083 0.5825667 ]
 [0.58255763 0.58259469 0.58256537]
 [0.5825628  0.58257557 0.58257073]]
